apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ml-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-ml
  template:
    metadata:
      labels:
        app: fastapi-ml
    spec:
      containers:
        - name: fastapi-ml
          image: prajwalpatil18818/fastapi-ml:1.0

          envFrom:
            - configMapRef:
                name: model-config

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 5

          resources:
            requests:
              cpu: "500m"
            limits:
              cpu: "1"

          ports:
            - containerPort: 8000